---
packages:
  - build-essential
  - git
  - git-core
  - curl
  - openssl
  - libreadline6
  - libreadline6-dev
  - zlib1g
  - zlib1g-dev
  - libssl-dev
  - libyaml-dev
  - libxml2-dev
  - libxslt-dev
  - libgmp3-dev
  - autoconf
  - libc6-dev
  - ncurses-dev
  - automake
  - libtool
  - bison
  - subversion
  - pkg-config
  - libmagickwand-dev
  - imagemagick
  - libcurl4-openssl-dev
  - libxvidcore-dev
  - redis-server
  - nodejs
  - xfsprogs
  - libsqlite3-dev
  - libreoffice
