---
# ROLE: packages
# roles/packages/tasks/main.yml
#
# updates, installs packages used by other installation/configuration tasks
#
- name: update apt cache
  become: yes
  package: update_cache=yes
  when: 
      (ansible_distribution == "Ubuntu") or
      (ansible_distribution == "Debian")

- name: install aptitude
  # on Debian Jessie aptitude is not installed by default, without it apt-get upgrade fails
  become: yes
  package: name=aptitude state=installed
  when: ansible_distribution == "Debian"

- name: upgrade existing apt/yum packages
  become: yes
  package: name=* state=latest

- name: include package list for distro
  include_vars: "{{ ansible_distribution }}.yml"

- name: install dev tools and libraries
  become: yes
  package: name={{ item }} state=installed
  with_items: "{{ packages }}"
