---
# ROLE: set_timezone
# roles/set_timezone/tasks/main.yml
#
# Sets the timezone persistently for the target host.  Defaults to America/New_York
# Usage:
#    - { role: set_timezone, timezone: America/Chicago  }
# the timezone must be a valid zone for your distribution - see http://www.iana.org/time-zones for the definitive list

- name: Write timezone to /etc/timezone
  become: yes
  template: src=timezone
        dest=/etc/timezone
        owner=root
        group=root
        mode=0644

- name: update timezone via dpkg
  become: yes
  command: dpkg-reconfigure --frontend noninteractive tzdata
  when:
      (ansible_distribution == "Ubuntu") or
      (ansible_distribution == "Debian")

- name: update timezone via timedatectl
  become: yes
  command: timedatectl set-timezone {{ timezone }}
  when: ansible_distribution == "CentOS"
