---
# Role: webserver/install
# roles/webserver/install/tasks/passenger.yml
# 
# Apache installation with passenger; install apached packages 
# see webserver/configure role for local configuration files
#
# adapted from
# https://github.com/akishin/ansible-playbooks/blob/master/lokka/roles/passenger/tasks/main.yml

- name: install passenger gem
  become: yes
  gem: name=passenger user_install=no state=present version={{ passenger_ver }}

- name: install apache packages
  become: yes
  package: name={{ item }} state=present
  with_items:
    - apache2-prefork-dev
    - apache2-mpm-worker
  when: 
    (ansible_distribution == "Ubuntu") or
    (ansible_distribution == "Debian")

- name: symlink passenger utilities for root user
  become: yes
  file: src=/usr/local/bin/{{ item }} dest=/usr/sbin/{{ item }} state=link
  with_items:
      - passenger
      - passenger-config
      - passenger-install-apache2-module
      - passenger-install-nginx-module
      - passenger-memory-stats
      - passenger-status
  when: ansible_distribution == "CentOS"

- name: install passenger-install-apache2-module
  become: yes
  shell: passenger-install-apache2-module --auto creates=/usr/local/lib/ruby/gems/{{ ruby_ver | regex_replace (".\d+$", ".0") }}/gems/passenger-{{ passenger_ver }}/buildout/apache2/mod_passenger.so

- name: generate passenger.conf file
  become: yes
  shell: passenger-install-apache2-module --snippet > "{{ passenger_root }}/passenger.conf" creates="{{ passenger_root }}/passenger.conf"

- name: symlink passenger config
  become: yes
  file: src=/etc/apache2/conf-available/passenger.conf path=/etc/apache2/conf-enabled/passenger.conf state=link
  when: 
    (ansible_distribution == "Ubuntu") or
    (ansible_distribution == "Debian")

- name: restart apache
  become: yes
  service: name="{{ apache }}" state=restarted
